### ISSUE TITLE
fix AutoFocus Directive

### ISSUE THREAD

**Issue by simonmumenthaler** [shiftcode/sc-ng-commons-public#7]
The `scAutoFocus` directive currently sets `tabindex` to `-1` if no `tabindex` is set.
This is problematic when the directive is used on a natively focusable element like button or input fields.
When setting tabindex to -1 the element is no longer accessible via tab.

**Comment by michaelwittwer** [comment]
@simonmumenthaler can we close this, since https://github.com/shiftcode/sc-ng-commons-public/commit/55c6b1ce6d4f8405c1c2618310d48cbdd7b7755e is included in the latest release?
